route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - text: "{{ .CommonAnnotations.summary }}"
        api_url: 'https://hooks.slack.com/services/...'
        channel: 'alert'
        send_resolved: true
