route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - text: "{{ .CommonAnnotations.summary }}"
        api_url: 'https://hooks.slack.com/services/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'
        channel: 'alert'
        send_resolved: true